name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./AWSLambdaPOC.sln
    - name: Build
      run: dotnet build ./AWSLambdaPOC/AWSLambdaPOC.csproj --no-restore --configuration Release
    - name: Publish
      run: dotnet publish ./AWSLambdaPOC/AWSLambdaPOC.csproj --no-restore --output AWSLambdaPOC_Publish --configuration Release
    # - name: Test
     # run: dotnet test --no-build --verbosity normal
